// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDphpYZLP_cHDByLqc5EbY7uHCG6Wmm_jY',
    appId: '1:320127219513:web:2a24f09e6a92075483dae8',
    messagingSenderId: '320127219513',
    projectId: 'lovelymeal1-7a2a9',
    authDomain: 'lovelymeal1-7a2a9.firebaseapp.com',
    storageBucket: 'lovelymeal1-7a2a9.firebasestorage.app',
    measurementId: 'G-J5NM2V4QJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw5JuDudjHL4vgFBhXLuGLS94rraFGh3s',
    appId: '1:320127219513:android:c75e2c255a649da383dae8',
    messagingSenderId: '320127219513',
    projectId: 'lovelymeal1-7a2a9',
    storageBucket: 'lovelymeal1-7a2a9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDphpYZLP_cHDByLqc5EbY7uHCG6Wmm_jY',
    appId: '1:320127219513:web:20cc7e12f14dae8f83dae8',
    messagingSenderId: '320127219513',
    projectId: 'lovelymeal1-7a2a9',
    authDomain: 'lovelymeal1-7a2a9.firebaseapp.com',
    storageBucket: 'lovelymeal1-7a2a9.firebasestorage.app',
    measurementId: 'G-B24EPETKZN',
  );
}
